#!/bin/sh

Rscript -e "roxygen2::roxygenize()"

redoreadme=`git diff --name-only README.Rmd`
readmeredone=`git diff --name-only README.md`
if test "X$redoreadme" != "X"; then
  if test "X$readmeredone" = "X"; then
    Rscript -e "knitr::knit(input='README.Rmd', output='README.md')"
  fi
fi
